---
title: "Har en persons høyde innvirkning på lønna?"
subtitle: "Assignment 2 i MSB105 Data Science - innleveringsfrist 12.10.20"
author: 
  - Katrine Hope
  - Karl-Gunnar Severinsen
classoption: twoside
fontsize: 12pt
linestretch: 1.5
output: html_notebook
---


```{r setup, echo = FALSE}
library(modelr)
library(ggplot2)
library(knitr)
library(tinytex)
library(tidyverse)
library(ggpubr)
library(dplyr)
```

## Introduksjon


## Analyse

Vi starter med å lage en kolonne der høyden er vist i centimeter. 
Vi gjør dette for å kunne få en bedre og mer forståelig analyse, da vi vil få en bedre forståelse ved å benytte kjente verdier. 
Deretter sorterer vi utvalget i datasettet inn i 10 intervaller med sammendragsstatistikk, for å gi en kjapp oversikt:

```{r oversikt, echo=FALSE}
heights$height_cm <- heights$height*2.54
heights$height_cmInt <- cut(heights$height_cm, breaks = 8)
kable(summary(heights[,1:5]))
kable(summary(heights[,6:10]))
```

<<<<<<< HEAD
Her ser vi statistikk på inntekt, høyde, vekt, alder, ekteskapelig status, kjønn, utdanning. 
=======
Her ser vi statistikk på inntekt, høyde (i tommer), vekt, alder, sivilstatus, kjønn og utdanning og høyde (i cm).

>>>>>>> 4de0a416c27afb6110d6ea0104d7fcb807bfba04

## Referanser


